# Import statements and reading in the housing dataset into pandas DataFrame
- missing values exist in total bedrooms feature
- "ocean_proximity" feature has string values and must be converted to numerical values

In [1]:
# Import statements
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.base import BaseEstimator, RegressorMixin
from sklearn.metrics import accuracy_score
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import r2_score
import tensorflow as tf
from tensorflow.keras.layers import *
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import backend as K
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint
from tensorflow.keras import regularizers
from tensorflow.keras.losses import MeanSquaredError
from tensorflow.keras.metrics import mean_squared_logarithmic_error, mean_squared_error, mean_absolute_error
from tensorflow.keras.models import Sequential
from tensorflow.keras.wrappers.scikit_learn import KerasRegressor

# Load and read housing data set into pandas dataframe 
housingDF = pd.read_csv("housing.csv")

# Print information about dataframe
housingDF.info()
display(housingDF)

# Drop the rows in the dataset with null values
housingDF = housingDF.dropna()
housingDF.info()
display(housingDF)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object
dtypes: float64(9), object(1)
memory usage: 1.6+ MB

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

<class 'pandas.core.frame.DataFrame'>
Int64Index: 20433 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20433 non-null  float64
 1   latitude            20433 non-null  float64
 2   housing_median_age  20433 non-null  float64
 3   total_rooms         20433 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20433 non-null  float64
 6   households          20433 non-null  float64
 7   median_income       20433 non-null  float64
 8   median_house_value  20433 non-null  float64
 9   ocean_proximity     20433 non-null  object
dtypes: float64(9), object(1)
memory usage: 1.7+ MB

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

## Converting "ocean proximity" attribute to numerical feature
- Since ANN prefers to work with numbers, we encode the string categories by numbers
- 5 categories converted to 5 numerics

In [2]:
lb_encoder = LabelEncoder()
housingDF['ocean_proximity'] = lb_encoder.fit_transform(housingDF['ocean_proximity'])

# Display the column and its details after transformation
display(housingDF['ocean_proximity'])
display(housingDF['ocean_proximity'].unique())

0        3
1        3
2        3
3        3
4        3
        ..
20635    1
20636    1
20637    1
20638    1
20639    1
Name: ocean_proximity, Length: 20433, dtype: int32

array([3, 0, 1, 4, 2])

# Scale the data, then split it into training and testing sets
### Use of SKLearn library to scale then split the data into training and testing sets
- Training (2/3)
- Testing (1/3)

In [3]:
# Split the labels and features in original dataset
features = housingDF.drop("median_house_value", axis=1)
display(features)
labels = housingDF["median_house_value"].copy()

# Scale the continuous features using StandardScaler class
for column in features:
    if features[column].dtypes == 'float64':
        features[column] = StandardScaler().fit_transform(features[column].values.reshape(-1, 1))
print("After scaling continuous features:")
display(features)

# Call train_test_split function from sklearn library to split the dataset randomly
X_train, X_test, Y_train, Y_test = train_test_split(features, labels, test_size=1/3, random_state=42)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,3
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,3
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,3
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,3
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,3
...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,1
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,1
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,1
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,1
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,1

After scaling continuous features:

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity
0,-1.327314,1.051717,0.982163,-0.803813,-0.970325,-0.973320,-0.976833,2.345163,3
1,-1.322323,1.042355,-0.606210,2.042130,1.348276,0.861339,1.670373,2.332632,3
2,-1.332305,1.037674,1.855769,-0.535189,-0.825561,-0.819769,-0.843427,1.782939,3
3,-1.337296,1.037674,1.855769,-0.623510,-0.718768,-0.765056,-0.733562,0.932970,3
4,-1.337296,1.037674,1.855769,-0.461970,-0.611974,-0.758879,-0.628930,-0.013143,3
...,...,...,...,...,...,...,...,...,...
20635,-0.758318,1.800677,-0.288535,-0.444580,-0.388895,-0.511787,-0.443207,-1.216727,1
20636,-0.818212,1.805358,-0.844466,-0.887557,-0.920488,-0.943315,-1.008223,-0.692044,1
20637,-0.823203,1.777272,-0.923885,-0.175042,-0.125472,-0.368826,-0.173778,-1.143171,1
20638,-0.873115,1.777272,-0.844466,-0.355344,-0.305834,-0.603564,-0.393506,-1.055136,1
20639,-0.833186,1.749186,-1.003304,0.067955,0.185416,-0.033487,0.079956,-0.780606,1

# Wrapping the Keras ANN model around a custom SKLearn Regressor

In [5]:
class ANNRegressor(BaseEstimator, RegressorMixin):
    # Constructor to instantiate default or user-defined values
    def __init__(self, in_features=10, num_hidden=1, num_neurons=30, epochs=50, 
                    batch_norm=False, early_stopping=True, verbose=1):
        self.in_features = in_features
        self.num_hidden = num_hidden
        self.num_neurons = num_neurons
        self.batch_norm = batch_norm
        self.epochs = epochs
        self.early_stopping = early_stopping
        self.verbose = verbose
        
        # Build the ANN
        self.model = ANNRegressor.build_model(self.in_features, self.num_hidden, self.num_neurons, self.batch_norm)
        
    @staticmethod
    def build_model(in_features, num_hidden, num_neurons, batch_norm):
        model = Sequential()
        
        # Input layer
        model.add(Dense(num_neurons, input_shape=(in_features,), activation='relu'))

        # Add hidden layers to model
        if (num_hidden > 1):
            for i in range(num_hidden - 1):
                model.add(Dense(num_neurons, activation='relu'))
                if(batch_norm):
                    model.add(BatchNormalization())

        # Output layer
        model.add(Dense(1))
        
        return model
        
    def fit(self, X, Y):
        # Split into training and validating sets
        X_train, X_val, Y_train, Y_val = train_test_split(X, Y, test_size=1/3)
        
        # Specifies callbacks list
        callbacks = [
            ModelCheckpoint('model.weights.hdf5', save_best_only=True, verbose=self.verbose)
        ]
        
        # Use early stopping to stop training when validation error reaches minimum
        if(self.early_stopping):
            callbacks.append(EarlyStopping(monitor='val_loss', patience=10, verbose=self.verbose))
        
        # Compile the model then train
        adam = Adam(learning_rate=0.001)
        self.model.compile(optimizer=adam, loss='mse')
        self.model.fit(X_train, Y_train, validation_data=(X_val, Y_val), epochs=self.epochs, 
                       callbacks=callbacks, verbose=self.verbose)
        
    def predict(self, X):
        predictions = self.model.predict(X)
        
        return predictions

# Instantiate the model and train the model using the training dataset

In [13]:
annRegressor = ANNRegressor(in_features=X_train.shape[1], num_hidden=10, num_neurons=80, epochs=30, verbose=1)
annRegressor.fit(X_train, Y_train)

Epoch 1/30
272/284 [===========================>..] - ETA: 0s - loss: 17951879168.0000
Epoch 1: val_loss improved from inf to 5731935232.00000, saving model to model.weights.hdf5
284/284 [==============================] - 3s 8ms/step - loss: 17452351488.0000 - val_loss: 5731935232.0000
Epoch 2/30
268/284 [===========================>..] - ETA: 0s - loss: 5268873216.0000
Epoch 2: val_loss improved from 5731935232.00000 to 4578470400.00000, saving model to model.weights.hdf5
284/284 [==============================] - 2s 7ms/step - loss: 5221924352.0000 - val_loss: 4578470400.0000
Epoch 3/30
273/284 [===========================>..] - ETA: 0s - loss: 4565912576.0000
Epoch 3: val_loss improved from 4578470400.00000 to 4059962624.00000, saving model to model.weights.hdf5
284/284 [==============================] - 1s 2ms/step - loss: 4555992576.0000 - val_loss: 4059962624.0000
Epoch 4/30
263/284 [==========================>...] - ETA: 0s - loss: 4341251072.0000
Epoch 4: val_loss improved from 4059962624.00000 to 3997685760.00000, saving model to model.weights.hdf5
284/284 [==============================] - 1s 2ms/step - loss: 4291905536.0000 - val_loss: 3997685760.0000
Epoch 5/30
265/284 [==========================>...] - ETA: 0s - loss: 4106560000.0000
Epoch 5: val_loss improved from 3997685760.00000 to 3747533568.00000, saving model to model.weights.hdf5
284/284 [==============================] - 1s 2ms/step - loss: 4106951936.0000 - val_loss: 3747533568.0000
Epoch 6/30
269/284 [===========================>..] - ETA: 0s - loss: 4001799936.0000
Epoch 6: val_loss did not improve from 3747533568.00000
284/284 [==============================] - 0s 2ms/step - loss: 3966324224.0000 - val_loss: 4210549248.0000
Epoch 7/30
282/284 [============================>.] - ETA: 0s - loss: 3906611200.0000
Epoch 7: val_loss did not improve from 3747533568.00000
284/284 [==============================] - 1s 2ms/step - loss: 3903365376.0000 - val_loss: 3797512192.0000
Epoch 8/30
277/284 [============================>.] - ETA: 0s - loss: 3856226304.0000
Epoch 8: val_loss improved from 3747533568.00000 to 3458793472.00000, saving model to model.weights.hdf5
284/284 [==============================] - 1s 3ms/step - loss: 3855159296.0000 - val_loss: 3458793472.0000
Epoch 9/30
267/284 [===========================>..] - ETA: 0s - loss: 3703549696.0000
Epoch 9: val_loss improved from 3458793472.00000 to 3425555456.00000, saving model to model.weights.hdf5
284/284 [==============================] - 1s 2ms/step - loss: 3689622016.0000 - val_loss: 3425555456.0000
Epoch 10/30
258/284 [==========================>...] - ETA: 0s - loss: 3638069760.0000
Epoch 10: val_loss did not improve from 3425555456.00000
284/284 [==============================] - 1s 2ms/step - loss: 3626752000.0000 - val_loss: 3815175424.0000
Epoch 11/30
265/284 [==========================>...] - ETA: 0s - loss: 3681028608.0000
Epoch 11: val_loss did not improve from 3425555456.00000
284/284 [==============================] - 1s 2ms/step - loss: 3648274432.0000 - val_loss: 3535000832.0000
Epoch 12/30
266/284 [===========================>..] - ETA: 0s - loss: 3647052032.0000
Epoch 12: val_loss did not improve from 3425555456.00000
284/284 [==============================] - 1s 2ms/step - loss: 3595708160.0000 - val_loss: 3525429504.0000
Epoch 13/30
270/284 [===========================>..] - ETA: 0s - loss: 3525445888.0000
Epoch 13: val_loss improved from 3425555456.00000 to 3334136832.00000, saving model to model.weights.hdf5
284/284 [==============================] - 5s 17ms/step - loss: 3557912832.0000 - val_loss: 3334136832.0000
Epoch 14/30
266/284 [===========================>..] - ETA: 0s - loss: 3562915584.0000
Epoch 14: val_loss did not improve from 3334136832.00000
284/284 [==============================] - 0s 2ms/step - loss: 3539716864.0000 - val_loss: 3491825664.0000
Epoch 15/30
267/284 [===========================>..] - ETA: 0s - loss: 3441694720.0000
Epoch 15: val_loss improved from 3334136832.00000 to 3306079232.00000, saving model to model.weights.hdf5
284/284 [==============================] - 11s 40ms/step - loss: 3450063104.0000 - val_loss: 3306079232.0000
Epoch 16/30
265/284 [==========================>...] - ETA: 0s - loss: 3447524352.0000
Epoch 16: val_loss improved from 3306079232.00000 to 3280932864.00000, saving model to model.weights.hdf5
284/284 [==============================] - 1s 2ms/step - loss: 3428780032.0000 - val_loss: 3280932864.0000
Epoch 17/30
251/284 [=========================>....] - ETA: 0s - loss: 3431840256.0000
Epoch 17: val_loss did not improve from 3280932864.00000
284/284 [==============================] - 1s 2ms/step - loss: 3438870016.0000 - val_loss: 3289908992.0000
Epoch 18/30
262/284 [==========================>...] - ETA: 0s - loss: 3392862720.0000
Epoch 18: val_loss did not improve from 3280932864.00000
284/284 [==============================] - 1s 2ms/step - loss: 3388623616.0000 - val_loss: 3354621696.0000
Epoch 19/30
268/284 [===========================>..] - ETA: 0s - loss: 3410045440.0000
Epoch 19: val_loss improved from 3280932864.00000 to 3131398144.00000, saving model to model.weights.hdf5
284/284 [==============================] - 6s 22ms/step - loss: 3411427072.0000 - val_loss: 3131398144.0000
Epoch 20/30
267/284 [===========================>..] - ETA: 0s - loss: 3297172992.0000
Epoch 20: val_loss did not improve from 3131398144.00000
284/284 [==============================] - 0s 2ms/step - loss: 3307785472.0000 - val_loss: 3181653248.0000
Epoch 21/30
264/284 [==========================>...] - ETA: 0s - loss: 3304152064.0000
Epoch 21: val_loss did not improve from 3131398144.00000
284/284 [==============================] - 1s 2ms/step - loss: 3282052096.0000 - val_loss: 3305123328.0000
Epoch 22/30
263/284 [==========================>...] - ETA: 0s - loss: 3220650240.0000
Epoch 22: val_loss did not improve from 3131398144.00000
284/284 [==============================] - 0s 2ms/step - loss: 3245459968.0000 - val_loss: 3423534080.0000
Epoch 23/30
268/284 [===========================>..] - ETA: 0s - loss: 3187595008.0000
Epoch 23: val_loss did not improve from 3131398144.00000
284/284 [==============================] - 0s 2ms/step - loss: 3234891776.0000 - val_loss: 3167139072.0000
Epoch 24/30
262/284 [==========================>...] - ETA: 0s - loss: 3254942208.0000
Epoch 24: val_loss improved from 3131398144.00000 to 3022245632.00000, saving model to model.weights.hdf5
284/284 [==============================] - 1s 2ms/step - loss: 3268818176.0000 - val_loss: 3022245632.0000
Epoch 25/30
268/284 [===========================>..] - ETA: 0s - loss: 3222251520.0000
Epoch 25: val_loss did not improve from 3022245632.00000
284/284 [==============================] - 1s 2ms/step - loss: 3223943168.0000 - val_loss: 3096523776.0000
Epoch 26/30
261/284 [==========================>...] - ETA: 0s - loss: 3241662976.0000
Epoch 26: val_loss did not improve from 3022245632.00000
284/284 [==============================] - 1s 2ms/step - loss: 3197259264.0000 - val_loss: 3135448576.0000
Epoch 27/30
270/284 [===========================>..] - ETA: 0s - loss: 3109772800.0000
Epoch 27: val_loss did not improve from 3022245632.00000
284/284 [==============================] - 0s 2ms/step - loss: 3130109696.0000 - val_loss: 3079377920.0000
Epoch 28/30
265/284 [==========================>...] - ETA: 0s - loss: 3084866816.0000
Epoch 28: val_loss did not improve from 3022245632.00000
284/284 [==============================] - 0s 2ms/step - loss: 3095005952.0000 - val_loss: 3236536576.0000
Epoch 29/30
268/284 [===========================>..] - ETA: 0s - loss: 3233483264.0000
Epoch 29: val_loss did not improve from 3022245632.00000
284/284 [==============================] - 0s 2ms/step - loss: 3211049984.0000 - val_loss: 3050248960.0000
Epoch 30/30
283/284 [============================>.] - ETA: 0s - loss: 3168233728.0000
Epoch 30: val_loss improved from 3022245632.00000 to 2995559936.00000, saving model to model.weights.hdf5
284/284 [==============================] - 2s 8ms/step - loss: 3167122944.0000 - val_loss: 2995559936.0000

In [14]:
# Method to display model evaluation metrics
def display_model_metrics(label, predictions):
    # The mean absolute error
    print("Mean absolute error: %.4f\n" % mean_absolute_error(label, predictions))

    # The mean squared error
    print("Root mean squared error: %.4f\n" % np.sqrt(mean_squared_error(label, predictions)))

    # The coefficient of determination: 1 is perfect prediction R^2
    print("Coefficient of determination: %.4f\n" % r2_score(label, predictions))

predictions = annRegressor.predict(X_test)
display(Y_test)
display(predictions)

display_model_metrics(Y_test, predictions[:,-1])

213/213 [==============================] - 0s 965us/step

14416    245800.0
16383    137900.0
7731     218200.0
1410     220800.0
1335     170500.0
           ...
20058     43700.0
4394     200000.0
20320    186800.0
10601    342900.0
15573    239100.0
Name: median_house_value, Length: 6811, dtype: float64

array([[184407.83],
       [148662.55],
       [215976.73],
       ...,
       [198148.42],
       [351217.03],
       [195242.58]], dtype=float32)

Mean absolute error: 38737.4492

Root mean squared error: 55634.4648

Coefficient of determination: 0.7678